Repository RhyenSftwareEngr/SampleForDemo, pull requests merged in 2023-12, with the labels that each got.

#2 Fix: Update addNumbers method
  Main.java
Labels: help wanted

#3 Feat: Add Divide method
  Main.java
Labels: enhancement

#4 Feat: add Subtract method
  Main.java
Labels: enhancement

#5 Feat: Adds remainderNumbers method
  Main.java
Labels: enhancement

#7 Fix: Changes the method name of addNumbers to add_Numbers
  Main.java
Labels: Naming Convention

#9 Fix: Changes naming convention for subrtractNumbers method
  Main.java
Labels: Naming Convention

#11 Fix: Changes mehtod name of divideNumbers
  Main.java
Labels: Naming Convention
